require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/migrate/*
    - db/schema.rb
  NewCops: enable

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Max: 160
  Exclude:
    - config/routes.rb

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable

Lint/UnusedMethodArgument:
  Exclude:
    - app/interactors/**/*.rb

Lint/EmptyFile:
  Exclude:
    - Dangerfile
    - db/seeds.rb

Lint/UselessAccessModifier:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 15

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 30

RSpec/NamedSubject:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/CollectionMethods:
  PreferredMethods:
    find: "detect"

Style/ClassAndModuleChildren:
  Include:
    - lib/**/*.rb

Style/Documentation:
  Enabled: false
